const tailwindFlexboxOptions = {
  "flex-direction": {
    "flex-row": "row",
    "flex-row-reverse": "row-reverse",
    "flex-col": "column",
    "flex-col-reverse": "column-reverse",
  },
  "flex-wrap": {
    "flex-wrap": "wrap",
    "flex-wrap-reverse": "wrap-reverse",
    "flex-nowrap": "nowrap",
  },
  "justify-content": {
    "justify-start": "flex-start",
    "justify-end": "flex-end",
    "justify-center": "center",
    "justify-between": "space-between",
    "justify-around": "space-around",
    "justify-evenly": "space-evenly",
  },
  "align-items": {
    "items-start": "flex-start",
    "items-end": "flex-end",
    "items-center": "center",
    "items-baseline": "baseline",
    "items-stretch": "stretch",
  },
  "align-content": {
    "content-start": "flex-start",
    "content-end": "flex-end",
    "content-center": "center",
    "content-between": "space-between",
    "content-around": "space-around",
    "content-evenly": "space-evenly",
  },
  gap: {
    "gap-0": "0px",
    "gap-px": "1px",
    "gap-0.5": "0.125rem",
    "gap-1": "0.25rem",
    "gap-1.5": "0.375rem",
    "gap-2": "0.5rem",
    "gap-2.5": "0.625rem",
    "gap-3": "0.75rem",
    "gap-3.5": "0.875rem",
    "gap-4": "1rem",
    "gap-5": "1.25rem",
    "gap-6": "1.5rem",
    "gap-7": "1.75rem",
    "gap-8": "2rem",
    "gap-9": "2.25rem",
    "gap-10": "2.5rem",
    "gap-11": "2.75rem",
    "gap-12": "3rem",
    "gap-14": "3.5rem",
    "gap-16": "4rem",
    "gap-20": "5rem",
    "gap-24": "6rem",
    "gap-28": "7rem",
    "gap-32": "8rem",
    "gap-36": "9rem",
    "gap-40": "10rem",
    "gap-44": "11rem",
    "gap-48": "12rem",
    "gap-52": "13rem",
    "gap-56": "14rem",
    "gap-60": "15rem",
    "gap-64": "16rem",
    "gap-72": "18rem",
    "gap-80": "20rem",
    "gap-96": "24rem",
  },
  "place-content": {
    "place-content-center": "center",
    "place-content-start": "start",
    "place-content-end": "end",
    "place-content-between": "space-between",
    "place-content-around": "space-around",
    "place-content-evenly": "space-evenly",
    "place-content-stretch": "stretch",
  },
  "place-items": {
    "place-items-start": "start",
    "place-items-end": "end",
    "place-items-center": "center",
    "place-items-stretch": "stretch",
  },
};

export default tailwindFlexboxOptions;
