const tailwindFlexboxOptions = {
  flexDirection: [
    "flex-row",
    "flex-row-reverse",
    "flex-col",
    "flex-col-reverse",
  ],
  flexWrap: ["flex-wrap", "flex-wrap-reverse", "flex-nowrap"],
  justifyContent: [
    "justify-start",
    "justify-end",
    "justify-center",
    "justify-between",
    "justify-around",
    "justify-evenly",
  ],
  alignItems: [
    "items-start",
    "items-end",
    "items-center",
    "items-baseline",
    "items-stretch",
  ],
  alignContent: [
    "content-start",
    "content-end",
    "content-center",
    "content-between",
    "content-around",
    "content-evenly",
  ],
  gap: [
    "gap-0",
    "gap-px",
    "gap-0.5",
    "gap-1",
    "gap-1.5",
    "gap-2",
    "gap-2.5",
    "gap-3",
    "gap-3.5",
    "gap-4",
    "gap-5",
    "gap-6",
    "gap-7",
    "gap-8",
    "gap-9",
    "gap-10",
    "gap-11",
    "gap-12",
    "gap-14",
    "gap-16",
    "gap-20",
    "gap-24",
    "gap-28",
    "gap-32",
    "gap-36",
    "gap-40",
    "gap-44",
    "gap-48",
    "gap-52",
    "gap-56",
    "gap-60",
    "gap-64",
    "gap-72",
    "gap-80",
    "gap-96",
  ],
  placeContent: [
    "place-content-center",
    "place-content-start",
    "place-content-end",
    "place-content-between",
    "place-content-around",
    "place-content-evenly",
    "place-content-stretch",
  ],
  placeItems: [
    "place-items-start",
    "place-items-end",
    "place-items-center",
    "place-items-stretch",
  ],
};

export default tailwindFlexboxOptions;
